stages:
  - test

frontend:
  image: node:12.18-alpine3.12
  stage: test
  script:
    - yarn install
    - yarn test
  cache:
    key: ${CI_COMMIT_REF_SLUG}-node
    paths:
      - node_modules/
  artifacts:
    paths:
      - build/index.js
      - build/index.es.js
      - build/index.d.ts
    reports:
      junit: junit.xml
  tags:
    - gnm
    - docker
  only:
    - master
    - merge_requests
