/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const OAuthConfigurationIF = t.iface([], {
  "clientId": "string",
  "resource": "string",
  "oAuthUri": "string",
  "tokenUri": "string",
  "adminClaimName": "string",
});

const exportedTypeSuite: t.ITypeSuite = {
  OAuthConfigurationIF,
};
export default exportedTypeSuite;
